name: Destroy Terraform Infrastructure

# Trigger this workflow manually from the GitHub UI
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        name: "Authenticate to AWS Cloud"
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: true
          terraform_version: 1.9.5

      - name: Terraform fmt
        # working-directory: ./
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        # working-directory: ./
        id: init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=pe-pairing-tfstate" \
            -backend-config="key=pe-pairing-terraform.tfstate" \
            -backend-config="region=eu-west-2" \
            -backend-config="dynamodb_table=pe-pairing-tfstate-lock"

      # Generate a destroy plan
      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan.destroy

      # Apply the destroy plan
      - name: Terraform Destroy
        run: terraform apply -auto-approve tfplan.destroy